import type { CanonCharacter } from "../eras";

export const aegonConquestCharacters: CanonCharacter[] = [
  {
    id: "loren-lannister",
    name: "Loren Lannister",
    tuocVi: "Vua",
    house: "Lannister",
    role: "Vua Vùng Đá (King of the Rock)",
    religion: "Thất Diện Thần",
    blurb: "Vua của vùng Westerlands. Ông đã liên minh với vua Mern IX Gardener để tạo ra đội quân lớn nhất lịch sử nhằm chống lại đội quân của Aegon Targaryen. Nhưng liệu vàng và giáo mác có thể cản được lửa rồng?",
    birthYear: -25,
    deathYear: 15,
    age: 25,
    coreStats: { STR: 13, AGI: 12, END: 13, INT: 14, WIL: 14, CHA: 15 },
    talentIds: ["born-leader", "wealthy"],
    skills: { "Chỉ Huy": 10, "Ngoại Giao": 10, "Cận Chiến (Kiếm)": 8 },
    equipment: [],
    items: [{ ten: "Vàng Casterly Rock", soLuong: 1000, moTa: "Số vàng lớn mang theo từ quê nhà." }],
    gold: 5000,
    startingHookIds: [],
    startHoldings: ["casterly-rock"],
    startRegions: ["the-westerlands"],
    personalHooks: [
      { id: "field-of-fire", title: "Cánh Đồng Lửa", year: "2 BC", numericYear: -2, desc: "Liên quân hai vị vua đã tập hợp. Trận chiến quyết định sắp diễn ra." }
    ]
  },
  {
    id: "mern-ix-gardener",
    name: "Mern IX Gardener",
    tuocVi: "Vua",
    house: "Gardener",
    role: "Vua Vùng Reach (King of the Reach)",
    religion: "Thất Diện Thần",
    blurb: "Vị vua cuối cùng của Nhà Gardener. Ông tự tin vào sức mạnh của hiệp sĩ vùng Reach và đã mang toàn bộ gia tộc mình ra chiến trường để dẹp tan tham vọng của lũ rồng Targaryen.",
    birthYear: -45,
    deathYear: -2,
    age: 45,
    coreStats: { STR: 14, AGI: 10, END: 15, INT: 12, WIL: 13, CHA: 14 },
    talentIds: ["born-leader", "arrogant"],
    skills: { "Chỉ Huy": 12, "Cận Chiến (Kiếm)": 10 },
    equipment: [],
    items: [],
    gold: 3000,
    startingHookIds: [],
    startHoldings: ["highgarden"],
    startRegions: ["the-reach"],
    personalHooks: [
      { id: "field-of-fire-mern", title: "Cánh Đồng Lửa", year: "2 BC", numericYear: -2, desc: "Ngươi dẫn đầu kỵ binh hùng hậu nhất Westeros, thề sẽ nghiền nát Aegon." }
    ]
  },
  {
    id: "sharra-arryn",
    name: "Sharra Arryn",
    tuocVi: "Vua",
    house: "Arryn",
    role: "Thái hậu Nhiếp chính",
    religion: "Thất Diện Thần",
    blurb: "Thái hậu nhiếp chính của vùng Vale, thay mặt con trai nhỏ tuổi Ronnel cai trị. Một người phụ nữ khôn ngoan, từng đề nghị cưới Aegon để bảo vệ sự độc lập của Vương quốc Núi và Thung Lũng.",
    birthYear: -30,
    age: 30,
    coreStats: { STR: 8, AGI: 10, END: 10, INT: 16, WIL: 15, CHA: 16 },
    talentIds: ["cunning", "diplomat"],
    skills: { "Ngoại Giao": 15, "Thuyết Phục": 12, "Quản Lý": 14 },
    equipment: [],
    items: [],
    gold: 1500,
    startingHookIds: [],
    startHoldings: ["the-eyrie"],
    startRegions: ["the-vale"],
    personalHooks: [
      { id: "sharra-proposal", title: "Lời Cầu Hôn Của Thái Hậu", year: "1 BC", numericYear: -1, desc: "Ngươi gửi thư cầu hôn Aegon Targaryen, hy vọng một liên minh thay vì chiến tranh." }
    ]
  },
  {
    id: "ronnel-arryn",
    name: "Ronnel Arryn",
    tuocVi: "Vua",
    house: "Arryn",
    role: "Vua Cậu Bé",
    religion: "Thất Diện Thần",
    blurb: "Vị vua cuối cùng của xứ Vale, còn được biết đến với cái tên 'Vua Cậu Bé'. Giấc mơ lớn nhất của cậu không phải là trị vì, mà là được cưỡi trên lưng một con rồng.",
    birthYear: -6,
    age: 6,
    coreStats: { STR: 6, AGI: 8, END: 8, INT: 10, WIL: 9, CHA: 12 },
    talentIds: ["innocent"],
    skills: { "Cưỡi Ngựa": 5 },
    equipment: [],
    items: [],
    gold: 100,
    startingHookIds: [],
    startHoldings: [],
    startRegions: [],
    personalHooks: [
      { id: "ronnel-dragon", title: "Ước Mơ Cưỡi Rồng", year: "1 AC", numericYear: 1, desc: "Visenya Targaryen đã bay đến Eyrie. Ngươi có thể thấy con rồng Vhagar vĩ đại ngoài sân." }
    ]
  },
  {
    id: "edmyn-tully",
    name: "Edmyn Tully",
    tuocVi: "Lãnh Chúa",
    house: "Tully",
    role: "Lãnh Chúa Riverrun",
    religion: "Thất Diện Thần",
    blurb: "Vị Lãnh chúa Riverrun đầu tiên đứng lên chống lại Harren the Black và tuyên bố trung thành với Aegon Targaryen. Người mở đường cho sự cai trị của Nhà Tully tại Riverlands.",
    birthYear: -40,
    age: 40,
    coreStats: { STR: 12, AGI: 11, END: 13, INT: 14, WIL: 14, CHA: 15 },
    talentIds: ["pragmatic", "born-leader"],
    skills: { "Chỉ Huy": 12, "Ngoại Giao": 10, "Cận Chiến (Kiếm)": 10 },
    equipment: [],
    items: [],
    gold: 1200,
    startingHookIds: [],
    startHoldings: ["riverrun"],
    startRegions: ["the-riverlands"],
    personalHooks: [
      { id: "edmyn-rebellion", title: "Khởi Nghĩa Riverlands", year: "2 BC", numericYear: -2, desc: "Harren the Black quá tàn bạo. Đã đến lúc Riverlands tìm một vị vua mới." }
    ]
  },
  {
    id: "vickon-greyjoy",
    name: "Vickon Greyjoy",
    tuocVi: "Lãnh Chúa",
    house: "Greyjoy",
    role: "Lãnh Chúa Quần Đảo Sắt",
    religion: "Thần Chết Chìm",
    blurb: "Sau khi gia tộc Hoare bị tiêu diệt tại Harrenhal, quần đảo Sắt chìm trong hỗn loạn. Vickon Greyjoy là người được các chúa đảo bầu lên để dẫn dắt họ trong kỷ nguyên mới.",
    birthYear: -35,
    age: 35,
    coreStats: { STR: 14, AGI: 12, END: 15, INT: 13, WIL: 15, CHA: 12 },
    talentIds: ["ironborn", "resilient"],
    skills: { "Hàng Hải": 15, "Cận Chiến (Rìu)": 12, "Chỉ Huy": 10 },
    equipment: [],
    items: [],
    gold: 800,
    startingHookIds: [],
    startHoldings: ["pyke"],
    startRegions: ["the-iron-islands"],
    personalHooks: [
      { id: "vickon-election", title: "Cuộc Bầu Cử Quần Đảo", year: "2 AC", numericYear: 2, desc: "Vua Harren đã chết. Lãnh chúa Quần Đảo Sắt cần một người đứng đầu, và Aegon cho phép họ tự chọn." }
    ]
  },
  {
    id: "meria-martell",
    name: "Meria Martell",
    tuocVi: "Vua",
    house: "Martell",
    role: "Cóc Vàng Xứ Dorne",
    religion: "Thất Diện Thần",
    blurb: "Nữ vương 80 tuổi, mù loà và hói đầu của Dorne. Bà kiên quyết không quỳ gối trước Aegon, tuyên bố: 'Unbowed, Unbent, Unbroken'. Bất chấp rồng, Dorne sẽ không bao giờ đầu hàng.",
    birthYear: -80,
    deathYear: 13,
    age: 80,
    coreStats: { STR: 5, AGI: 5, END: 10, INT: 18, WIL: 20, CHA: 16 },
    talentIds: ["stubborn", "strategic-mind"],
    skills: { "Ngoại Giao": 15, "Chiến Lược": 18, "Lịch Sử": 15 },
    equipment: [],
    items: [],
    gold: 2000,
    startingHookIds: [],
    startHoldings: ["sunspear"],
    startRegions: ["dorne"],
    personalHooks: [
      { id: "meria-defiance", title: "Cóc Vàng Thách Thức", year: "1 BC", numericYear: -1, desc: "Rhaenys Targaryen đến Sunspear trên lưng rồng Meraxes. Ngươi chuẩn bị gửi cho ả một lời từ chối thẳng thừng." }
    ]
  },
  {
    id: "nymor-martell",
    name: "Nymor Martell",
    tuocVi: "Vua",
    house: "Martell",
    role: "Người Kế Vị Dorne",
    religion: "Thất Diện Thần",
    blurb: "Con trai của Meria Martell. Sau nhiều năm chiến tranh đẫm máu với Aegon, ông quyết định tìm kiếm hòa bình để cứu lấy xứ Dorne đang rỉ máu.",
    birthYear: -40,
    deathYear: 35,
    age: 40,
    coreStats: { STR: 10, AGI: 10, END: 12, INT: 15, WIL: 14, CHA: 15 },
    talentIds: ["diplomat", "peace-maker"],
    skills: { "Ngoại Giao": 16, "Chính Trị": 14 },
    equipment: [],
    items: [],
    gold: 1500,
    startingHookIds: [],
    startHoldings: [],
    startRegions: [],
    personalHooks: [
      { id: "nymor-peace", title: "Lá Thư Hòa Bình", year: "13 AC", numericYear: 13, desc: "Mẹ ngươi đã mất. Đã đến lúc chấm dứt cuộc chiến đẫm máu này bằng một lá thư bí mật gửi cho Aegon." }
    ]
  },
  {
    id: "deria-martell",
    name: "Deria Martell",
    tuocVi: "Lãnh Chúa",
    house: "Martell",
    role: "Đại Sứ Hòa Bình",
    religion: "Thất Diện Thần",
    blurb: "Con gái của Nymor Martell, người được giao nhiệm vụ mang lá thư bí mật của cha đến King's Landing để đàm phán hòa bình với Aegon Targaryen.",
    birthYear: -15,
    age: 15,
    coreStats: { STR: 8, AGI: 12, END: 10, INT: 14, WIL: 16, CHA: 16 },
    talentIds: ["brave", "persuasive"],
    skills: { "Ngoại Giao": 14, "Can Đảm": 12 },
    equipment: [],
    items: [],
    gold: 500,
    startingHookIds: [],
    startHoldings: [],
    startRegions: [],
    personalHooks: [
      { id: "deria-envoy", title: "Hành Trình Đến King's Landing", year: "13 AC", numericYear: 13, desc: "Ngươi mang theo hộp sọ của rồng Meraxes và một lá thư mật, bước vào ngai vàng để thương lượng với kẻ thù." }
    ]
  },
  {
    id: "dickon-morrigen",
    name: "Dickon Morrigen",
    tuocVi: "Hiệp Sĩ",
    house: "Khác",
    role: "Hiệp Sĩ Quạ",
    religion: "Thất Diện Thần",
    blurb: "Dickon Morrigen, chỉ huy đội Vệ Binh của vua bão Argilac. Ông nổi tiếng dũng cảm nhưng đã phải bỏ mạng trong trận Last Storm trước quân đội của Orys Baratheon.",
    birthYear: -30,
    deathYear: 0,
    age: 30,
    coreStats: { STR: 15, AGI: 14, END: 16, INT: 10, WIL: 15, CHA: 10 },
    talentIds: ["brave", "loyal"],
    skills: { "Cận Chiến (Kiếm)": 14, "Chỉ Huy": 12 },
    equipment: [],
    items: [],
    gold: 100,
    startingHookIds: [],
    startHoldings: [],
    startRegions: [],
    personalHooks: [
      { id: "the-last-storm", title: "Cơn Bão Cuối Cùng", year: "1 BC", numericYear: -1, desc: "Orys Baratheon đang kéo quân tới. Ngươi sẽ tử chiến vì Vua Bão Argilac." }
    ]
  }
];
