import type { CanonCharacter } from "../eras";

export const blackfyreRebellionCharacters: CanonCharacter[] = [
  {
    id: "baelor-breakspear",
    origin: "Trưởng nam của Daeron II và Myriah Martell, Thái tử của Bảy Vương Quốc và tổng chỉ huy phe Hoàng gia.", culture: "Valyria hậu duệ, gắn bó với Dorne", bloodline: "Nhà Targaryen và Nymeros Martell", continent: "Westeros",
    appearance: "Tóc nâu sẫm, mắt nâu và gương mặt mang nét Dornish rõ rệt; vì vậy bị kẻ thù xúc phạm là 'Baelor Spear' trước khi tên Breakspear được tôn vinh.",
    name: "Baelor Breakspear",
    tuocVi: "Hoàng Tử",
    house: "Targaryen",
    role: "Hoàng Tử Dragonstone",
    religion: "Thất Diện Thần",
    blurb: "Con trai trưởng và là người thừa kế của vua Daeron II. Baelor mang nhiều nét của người mẹ xứ Dorne với mái tóc đen và làn da ngăm. Anh là một chỉ huy lỗi lạc, người đã đập tan quân Blackfyre tại Cánh Đồng Cỏ Đỏ.",
    birthYear: 170,
    deathYear: 209,
    age: 26,
    coreStats: { "Sức Mạnh": 15, "Nhanh Nhẹn": 14, "Thể Chất": 15, "Trí Tuệ": 16, "Tinh Tường": 15, "Uy Tín": 18 },
    năngLực: { "Võ Lực": 75, "Thống Soái": 90, "Trí Mưu": 80, "Ngoại Giao": 75 },
    talentIds: ["commander-instinct", "warrior-blood", "beloved"],
    skills: { "command": 9, "sword-shield": 8, "war-riding": 7, "persuasion": 8 },
    equipment: [],
    items: [],
    gold: 2000,
    startResources: {
      "Gỗ": 20,
      "Quặng Sắt": 10,
      "Đá": 20,
      "Lương Thực": 100,
      "Ngựa": 4,
      "Thép Valyria": 0
    }, startingHookIds: [],
    father: "daeron-ii", mother: "myriah-martell",
    spouse: "jena-dondarrion",
    children: ["valarr-targaryen", "matarys-targaryen"],
    siblings: ["aerys-i-targaryen", "rhaegel-targaryen", "maekar-i-targaryen"],
    allies: ["maekar-i-targaryen"],
    rivals: ["daemon-blackfyre"],
    liege: "daeron-ii",
    relationshipDetails: {
      "daemon-blackfyre": { type: "Kẻ Thù", trust: 0, affinity: 20, detail: "Người anh em tầng khác cha. Baelor kính trọng khả năng chiến đấu của Daemon nhưng không thể tha thứ sự phản loạn." },
      "maekar-i-targaryen": { type: "Em Trai", trust: 90, affinity: 80, detail: "Em trai ít nói nhưng trung thành. Tại Cánh Đồng Cỏ Đỏ, Maekar dẫn quân đánh bọc sườn cứu Baelor." },
      "daeron-ii": { type: "Cha", trust: 100, affinity: 100, detail: "Baelor là niềm tự hào lớn nhất của Daeron II. Mọi người đều tin Baelor sẽ là một vị vua vĩ đại." }
    },
    personalHooks: [
      { id: "baelor-redgrass", title: "Cánh Đồng Cỏ Đỏ", year: "196 AC", numericYear: 196, desc: "Ngươi dẫn đầu đội quân Dorne và Stormlands đánh bọc sườn phiến quân Blackfyre. Chiến thắng hay thảm bại phụ thuộc vào nhát chùy của ngươi." }
    ],
    startArmies: [
          { name: "Vệ Binh Rồng", type: "Bộ Binh", size: 1200, quality: "Tinh Nhuệ" },
          { name: "Đội Bắn Nỏ Bến Vua", type: "Cung Thủ", size: 300, quality: "Tinh Nhuệ" }
        ],
        startFleets: [
          { name: "Hạm Đội Đô Đốc", type: "Chiến Thuyền Nặng", size: 10, quality: "Tinh Nhuệ" }
        ],
      startRegions: [],
      startHoldings: [],
      holdingsLevel: {},
      baseIncome: 25
},
  {
    id: "maekar-i-targaryen",
    origin: "Hoàng tử thứ tư của Daeron II và Myriah Martell, em trai Baelor và chỉ huy một cánh quân trung thành.", culture: "Valyria hậu duệ, gắn bó với Dorne", bloodline: "Nhà Targaryen và Nymeros Martell", continent: "Westeros",
    appearance: "Tóc bạc-vàng và mắt tím của dòng Targaryen; vóc dáng nghiêm nghị, quân phong cứng rắn.",
    name: "Maekar Targaryen",
    tuocVi: "Hoàng Tử",
    house: "Targaryen",
    role: "Hoàng Tử Mùa Hè",
    religion: "Thất Diện Thần",
    blurb: "Con trai thứ tư của Daeron II. Khác với người anh Baelor hoàn hảo, Maekar gai góc, khắc nghiệt và mang nhiều mặc cảm. Dù vậy, cái đe của Maekar đã chặn đứng cuộc tiến công của phiến quân.",
    birthYear: 174,
    deathYear: 233,
    age: 22,
    coreStats: { "Sức Mạnh": 16, "Nhanh Nhẹn": 12, "Thể Chất": 16, "Trí Tuệ": 12, "Tinh Tường": 14, "Uy Tín": 10 },
    năngLực: { "Võ Lực": 80, "Thống Soái": 50, "Trí Mưu": 60, "Ngoại Giao": 70 },
    talentIds: ["iron-constitution", "warrior-blood", "strategist"],
    skills: { "axe-mace": 8, "command": 8 },
    equipment: [],
    items: [],
    gold: 1500,
    startResources: {
      "Gỗ": 20,
      "Quặng Sắt": 10,
      "Đá": 20,
      "Lương Thực": 100,
      "Ngựa": 4,
      "Thép Valyria": 0
    }, startingHookIds: [],
    father: "daeron-ii", mother: "myriah-martell",
    spouse: "dyanna-dayne",
    children: ["daeron-the-drunken", "aerion-brightflame", "aemon-targaryen", "aegon-v-targaryen", "daella-targaryen", "rhae-targaryen"],
    siblings: ["baelor-breakspear"],
    allies: ["baelor-breakspear"],
    rivals: ["daemon-blackfyre"],
    liege: "daeron-ii",
    relationshipDetails: {
      "baelor-breakspear": { type: "Anh Trai", trust: 80, affinity: 70, detail: "Maekar kính trọng Baelor nhưng ghen tị với sự hoàn hảo của anh. Bi kịch là Maekar vô tình giết Baelor tại Ashford." },
      "daemon-blackfyre": { type: "Kẻ Thù", trust: 0, affinity: 0, detail: "Kẻ phản loạn phải bị nghiền nát. Maekar là cái đe chắn đứng Bước Tiến của phản quân." }
    },
    personalHooks: [
      { id: "maekar-anvil", title: "Cái Đe Của Maekar", year: "196 AC", numericYear: 196, desc: "Bức tường khiên của ngươi phải đứng vững trước cuộc tấn công mãnh liệt của Bittersteel, tạo thành cái đe cho chiếc búa của Baelor đập xuống." }
    ],
    startArmies: [
          { name: "Vệ Binh Rồng", type: "Bộ Binh", size: 1200, quality: "Tinh Nhuệ" },
          { name: "Cung Thủ Vương Đô", type: "Cung Thủ", size: 300, quality: "Tinh Nhuệ" }
        ],
        startFleets: [
          { name: "Hạm Đội Đô Đốc", type: "Chiến Thuyền Nặng", size: 10, quality: "Tinh Nhuệ" }
        ],
      startRegions: [],
      startHoldings: [],
      holdingsLevel: {},
      baseIncome: 25
},
  {
    id: "shiera-seastar",
    origin: "Con ngoài giá thú được thừa nhận của Aegon IV và Serenei of Lys; chị/em cùng cha khác mẹ của Bloodraven và Bittersteel.", culture: "Lysene", bloodline: "Nhà Targaryen qua cha; dòng Lys qua mẹ", continent: "Westeros",
    appearance: "Một mắt xanh, một mắt nâu; mái tóc bạc-vàng pha những vệt vàng óng, nổi tiếng vì vẻ đẹp khác thường.",
    name: "Shiera Seastar",
    tuocVi: "Thường Dân",
    house: "Khác",
    role: "Ngôi Sao Biển",
    religion: "Thất Diện Thần",
    blurb: "Đứa con hoang xinh đẹp nhất của vua Aegon IV. Có hai màu mắt khác biệt và vẻ đẹp ma mị, Shiera luôn đứng giữa cuộc tình tay ba với Bloodraven và Bittersteel.",
    birthYear: 178,
    age: 18,
    coreStats: { "Sức Mạnh": 5, "Nhanh Nhẹn": 10, "Thể Chất": 8, "Trí Tuệ": 18, "Tinh Tường": 15, "Uy Tín": 20 },
    năngLực: { "Võ Lực": 25, "Thống Soái": 100, "Trí Mưu": 90, "Ngoại Giao": 75 },
    talentIds: ["master-liar", "greenseer", "learned"],
    skills: { "persuasion": 9, "greensight": 7, "deception": 10 },
    equipment: [],
    items: [{ ten: "Dây Chuyền Sao Biển", soLuong: 1, moTa: "Sợi dây chuyền bạc điểm những viên ngọc bích và ngọc lục bảo." }],
    gold: 500,
    startResources: {
      "Gỗ": 20,
      "Quặng Sắt": 10,
      "Đá": 20,
      "Lương Thực": 100,
      "Ngựa": 4,
      "Thép Valyria": 0
    }, startingHookIds: [],
    father: "aegon-iv-targaryen", mother: "serenei-of-lys",
    siblings: ["daemon-blackfyre", "bittersteel", "bloodraven"],
    allies: ["bloodraven"],
    rivals: [],
    relationshipDetails: {
      "bloodraven": { type: "Người Tình", trust: 80, affinity: 80, detail: "Bloodraven yêu Shiera điên cuồng. Cô nhận tình yêu của anh nhưng không bao giờ thuộc về ai." },
      "bittersteel": { type: "Đối Thủ", trust: 20, affinity: 30, detail: "Bittersteel cũng yêu Shiera, và sự từ chối của cô làm sâu thêm mối hận giữa Bittersteel và Bloodraven." }
    },
    personalHooks: [
      { id: "shiera-choice", title: "Lựa Chọn Của Ngôi Sao", year: "196 AC", numericYear: 196, desc: "Cả Bloodraven và Bittersteel đều cầu xin tình yêu của ngươi trước khi họ ra trận để chém giết lẫn nhau." }
    ],
    spouse: "",
    children: [],
    startArmies: [
          { name: "Dân Binh ", type: "Bộ Binh", size: 42, quality: "Mới Lập Đội" },
          { name: "Cung Thủ ", type: "Cung Thủ", size: 18, quality: "Mới Lập Đội" }
        ],
      startRegions: [],
      startHoldings: [],
      holdingsLevel: {},
      baseIncome: 25
},
  {
    id: "gwayne-corbray",
    origin: "Hiệp sĩ Nhà Corbray ở Heart's Home, cầm Lady Forlorn cho phe Blackfyre tại Cánh Đồng Cỏ Đỏ.", culture: "Người Vale", bloodline: "Nhà Corbray", continent: "Westeros",
    appearance: "Không có mô tả ngoại hình canon xác thực; được biết đến bởi thanh kiếm Valyria Lady Forlorn.",
    name: "Gwayne Corbray",
    tuocVi: "Hiệp Sĩ",
    house: "Corbray",
    role: "Hiệp Sĩ Vệ Vương",
    religion: "Thất Diện Thần",
    blurb: "Thành viên Vệ Vương, cầm thanh kiếm thép Valyria Lady Forlorn. Cuộc đấu tay đôi giữa ông và Daemon Blackfyre là một trong những trận chiến huyền thoại nhất.",
    birthYear: 165,
    deathYear: 196,
    age: 31,
    coreStats: { "Sức Mạnh": 15, "Nhanh Nhẹn": 16, "Thể Chất": 15, "Trí Tuệ": 10, "Tinh Tường": 14, "Uy Tín": 12 },
    năngLực: { "Võ Lực": 75, "Thống Soái": 60, "Trí Mưu": 50, "Ngoại Giao": 70 },
    talentIds: ["beloved", "duelist", "warrior-blood"],
    skills: { "sword-shield": 9, "war-riding": 7 },
    equipment: [{ slot: "Vũ Khí Chính", ten: "Lady Forlorn", phamChat: "Thép Valyria", thuocTinh: { "Sát Thương": 25 }, moTa: "Thanh kiếm Thép Valyria của Nhà Corbray." }],
    items: [],
    gold: 50,
    startResources: {
      "Gỗ": 100,
      "Quặng Sắt": 75,
      "Đá": 400,
      "Lương Thực": 400,
      "Ngựa": 24,
      "Thép Valyria": 0
    }, startingHookIds: [],
    allies: ["daeron-ii", "baelor-breakspear"],
    rivals: ["daemon-blackfyre"],
    liege: "daeron-ii",
    courtPosition: "Vệ Vương",
    relationshipDetails: {
      "daemon-blackfyre": { type: "Kẻ Thù", trust: 0, affinity: 30, detail: "Cuộc đấu tay đôi huyền thoại. Gwayne kính trọng kiếm thuật của Daemon nhưng không lay chuyển lòng trung thành." },
      "baelor-breakspear": { type: "Đồng Minh", trust: 100, affinity: 90, detail: "Gwayne chiến đấu vì Hoàng tử Baelor và vua Daeron. Danh dự trên hết." }
    },
    personalHooks: [
      { id: "corbray-duel", title: "Cuộc Đấu Huyền Thoại", year: "196 AC", numericYear: 196, desc: "Trực diện với Daemon Blackfyre. Lady Forlorn chạm trán thanh Blackfyre trong tiếng gầm thét của hàng vạn binh lính." }
    ],
    father: "",
    mother: "",
    spouse: "",
    children: [],
    siblings: [],
    startArmies: [
          { name: "Dân Binh ", type: "Bộ Binh", size: 42, quality: "Mới Lập Đội" },
          { name: "Cung Thủ ", type: "Cung Thủ", size: 18, quality: "Mới Lập Đội" }
        ],
      startRegions: [],
      startHoldings: [],
      holdingsLevel: {},
      baseIncome: 25
},
  {
    id: "quentyn-ball",
    origin: "Hiệp sĩ thường dân từng là thầy vũ khí của Red Keep; theo Daemon Blackfyre sau khi không được phong vào Kingsguard.", culture: "Người Crownlands", bloodline: "Không xác minh", continent: "Westeros",
    appearance: "Không có mô tả ngoại hình canon xác thực; biệt danh Fireball gắn với mái tóc đỏ rực.",
    name: "Quentyn Ball",
    tuocVi: "Hiệp Sĩ",
    house: "Ball",
    role: "Quả Cầu Lửa",
    religion: "Thất Diện Thần",
    blurb: "Được mệnh danh là 'Fireball'. Bị từ chối vị trí trong Vệ Vương, Quentyn mang mối thù sâu sắc và trở thành một trong những chỉ huy xuất sắc nhất của quân Blackfyre.",
    birthYear: 160,
    deathYear: 196,
    age: 36,
    coreStats: { "Sức Mạnh": 16, "Nhanh Nhẹn": 15, "Thể Chất": 16, "Trí Tuệ": 12, "Tinh Tường": 15, "Uy Tín": 14 },
    năngLực: { "Võ Lực": 80, "Thống Soái": 70, "Trí Mưu": 60, "Ngoại Giao": 75 },
    talentIds: ["warrior-blood", "hot-tempered", "berserker"],
    skills: { "sword-shield": 9, "command": 8 },
    equipment: [],
    items: [],
    gold: 200,
    startResources: {
      "Gỗ": 100,
      "Quặng Sắt": 50,
      "Đá": 100,
      "Lương Thực": 500,
      "Ngựa": 20,
      "Thép Valyria": 0
    }, startingHookIds: [],
    allies: ["daemon-blackfyre", "bittersteel"],
    rivals: ["daeron-ii"],
    liege: "daemon-blackfyre",
    relationshipDetails: {
      "daemon-blackfyre": { type: "Chủ", trust: 100, affinity: 100, detail: "Fireball coi Daemon là vị vua thực sự. Ông chiến đấu đến chết vì nhà Blackfyre." },
      "daeron-ii": { type: "Kẻ Thù", trust: 0, affinity: 0, detail: "Daeron từ chối chỗ Vệ Vương cho Quentyn. Mối thù này dẫn đến cuộc phản loạn." }
    },
    personalHooks: [
      { id: "fireball-strike", title: "Cơn Phẫn Nộ Của Fireball", year: "196 AC", numericYear: 196, desc: "Ngươi vượt sông Mander, đánh úp quân trung thành và tiêu diệt hoàn toàn gia tộc Lefford." }
    ],
    father: "",
    mother: "",
    spouse: "",
    children: [],
    siblings: [],
    startArmies: [
          { name: "Dân Binh ", type: "Bộ Binh", size: 42, quality: "Mới Lập Đội" },
          { name: "Cung Thủ ", type: "Cung Thủ", size: 18, quality: "Mới Lập Đội" }
        ],
      startRegions: [],
      startHoldings: [],
      holdingsLevel: {},
      baseIncome: 25
},
  {
    id: "robb-reyne",
    origin: "Hiệp sĩ Nhà Reyne của Castamere, một trong các chiến binh đứng về phía Daemon Blackfyre.", culture: "Người miền Tây", bloodline: "Nhà Reyne", continent: "Westeros",
    appearance: "Không có mô tả ngoại hình canon xác thực.",
    name: "Robb Reyne",
    tuocVi: "Hiệp Sĩ",
    house: "Reyne",
    role: "Sư Tử Đỏ",
    religion: "Thất Diện Thần",
    blurb: "Một hiệp sĩ hào hoa và là một trong những tay kiếm xuất sắc nhất thời đại, phục vụ dưới trướng Daemon Blackfyre.",
    birthYear: 168,
    age: 28,
    coreStats: { "Sức Mạnh": 15, "Nhanh Nhẹn": 16, "Thể Chất": 14, "Trí Tuệ": 10, "Tinh Tường": 12, "Uy Tín": 16 },
    năngLực: { "Võ Lực": 75, "Thống Soái": 80, "Trí Mưu": 50, "Ngoại Giao": 60 },
    talentIds: ["duelist", "hot-tempered", "highborn-charm"],
    skills: { "sword-shield": 8, "war-riding": 8 },
    equipment: [],
    items: [],
    gold: 800,
    startResources: {
      "Gỗ": 50,
      "Quặng Sắt": 150,
      "Đá": 150,
      "Lương Thực": 600,
      "Ngựa": 20,
      "Thép Valyria": 0
    }, startingHookIds: [],
    allies: ["daemon-blackfyre", "bittersteel"],
    rivals: ["daeron-ii", "damon-lannister"],
    personalHooks: [
      { id: "reyne-charge", title: "Tiếng Gầm Sư Tử Đỏ", year: "196 AC", numericYear: 196, desc: "Ngươi dẫn đầu kỵ binh tấn công vào sườn đội hình quân Targaryen." }
    ],
    father: "",
    mother: "",
    spouse: "",
    children: [],
    siblings: [],
    startArmies: [
          { name: "Dân Binh ", type: "Bộ Binh", size: 42, quality: "Mới Lập Đội" },
          { name: "Cung Thủ ", type: "Cung Thủ", size: 18, quality: "Mới Lập Đội" }
        ],
      startRegions: [],
      startHoldings: [],
      holdingsLevel: {},
      baseIncome: 25
},
  {
    id: "leo-tyrell",
    origin: "Leo 'Longthorn' Tyrell, Lãnh chúa Highgarden và Lord Paramount of the Mander trong thời kỳ nổi loạn.", culture: "Người Reach", bloodline: "Nhà Tyrell", continent: "Westeros",
    appearance: "Không có mô tả ngoại hình canon xác thực; biệt danh Longthorn phản ánh danh tiếng võ dũng.",
    name: "Leo Tyrell",
    tuocVi: "Đại Lãnh Chúa",
    house: "Tyrell",
    role: "Gai Dài",
    religion: "Thất Diện Thần",
    blurb: "Lãnh chúa Leo 'Longthorn' Tyrell, một hiệp sĩ lừng danh của giải đấu, và là người đã đánh bại phe Blackfyre tại vùng Reach, dù không đến kịp trận Cánh Đồng Cỏ Đỏ.",
    birthYear: 160,
    age: 36,
    coreStats: { "Sức Mạnh": 14, "Nhanh Nhẹn": 15, "Thể Chất": 14, "Trí Tuệ": 13, "Tinh Tường": 14, "Uy Tín": 16 },
    năngLực: { "Võ Lực": 70, "Thống Soái": 80, "Trí Mưu": 65, "Ngoại Giao": 70 },
    talentIds: ["duelist", "commander-instinct", "merchant-fortune"],
    skills: { "war-riding": 9, "sword-shield": 7, "command": 7 },
    equipment: [],
    items: [],
    gold: 4000,
    startResources: {
      "Gỗ": 750,
      "Quặng Sắt": 125,
      "Đá": 500,
      "Lương Thực": 10000,
      "Ngựa": 150,
      "Thép Valyria": 0
    }, startingHookIds: [],
    allies: ["daeron-ii", "baelor-breakspear"],
    rivals: ["daemon-blackfyre"],
    personalHooks: [
      { id: "longthorn-reach", title: "Bảo Vệ Vùng Reach", year: "196 AC", numericYear: 196, desc: "Trong khi các trận chiến lớn diễn ra ở phía Bắc, ngươi phải dọn dẹp các lãnh chúa phản nghịch ngay trong sân nhà mình." }
    ],
    startArmies: [
          { name: "Vạn Quân Highgarden", type: "Bộ Binh", size: 48000, quality: "Thành Thạo" },
          { name: "Đội Kỵ Sĩ Mùa Hè", type: "Kỵ Binh", size: 16000, quality: "Thành Thạo" },
          { name: "Người Bắn Nỏ Vùng Reach", type: "Cung Thủ", size: 16000, quality: "Thành Thạo" }
        ],
    father: "",
    mother: "",
    spouse: "",
    children: [],
    siblings: [],
      startRegions: ["the-reach"],
      startHoldings: ["the-reach-seat"],
      holdingsLevel: {"the-reach-seat":5},
      baseIncome: 700
},
  {
    id: "donnel-arryn",
    origin: "Hiệp sĩ Nhà Arryn của Vale, phục vụ phe Hoàng gia và tử trận tại Cánh Đồng Cỏ Đỏ.", culture: "Người Vale", bloodline: "Nhà Arryn", continent: "Westeros",
    appearance: "Không có mô tả ngoại hình canon xác thực.",
    name: "Donnel Arryn",
    tuocVi: "Đại Lãnh Chúa",
    house: "Arryn",
    role: "Lãnh Chúa Eyrie",
    religion: "Thất Diện Thần",
    blurb: "Người chỉ huy quân đội tiên phong của Targaryen tại Cánh Đồng Cỏ Đỏ, nhưng hàng ngũ của ông đã bị Daemon Blackfyre đập tan.",
    birthYear: 160,
    deathYear: 209,
    age: 36,
    coreStats: { "Sức Mạnh": 12, "Nhanh Nhẹn": 12, "Thể Chất": 13, "Trí Tuệ": 12, "Tinh Tường": 14, "Uy Tín": 14 },
    năngLực: { "Võ Lực": 60, "Thống Soái": 70, "Trí Mưu": 60, "Ngoại Giao": 70 },
    talentIds: ["warrior-blood", "commander-instinct"],
    skills: { "command": 7, "sword-shield": 6 },
    equipment: [],
    items: [],
    gold: 1500,
    startResources: {
      "Gỗ": 500,
      "Quặng Sắt": 375,
      "Đá": 2000,
      "Lương Thực": 2000,
      "Ngựa": 120,
      "Thép Valyria": 0
    }, startingHookIds: [],
    allies: ["daeron-ii", "baelor-breakspear"],
    rivals: ["daemon-blackfyre", "bittersteel"],
    personalHooks: [
      { id: "donnel-vanguard", title: "Tiên Phong Thất Bại", year: "196 AC", numericYear: 196, desc: "Ngươi dẫn quân tiên phong đối mặt với Daemon Blackfyre và thanh gươm của vương triều. Ngươi biết mình không có cơ hội." }
    ],
    startArmies: [
          { name: "Lính Giáo Thung Lũng", type: "Bộ Binh", size: 21000, quality: "Thành Thạo" },
          { name: "Kỵ Sĩ Thung Lũng", type: "Kỵ Binh", size: 7000, quality: "Thành Thạo" },
          { name: "Đội Bắn Nỏ Thung Lũng", type: "Cung Thủ", size: 7000, quality: "Thành Thạo" }
        ],
    father: "",
    mother: "",
    spouse: "",
    children: [],
    siblings: [],
      startRegions: ["the-vale"],
      startHoldings: ["the-vale-seat"],
      holdingsLevel: {"the-vale-seat":5},
      baseIncome: 400
},
  {
    id: "damon-lannister",
    origin: "Lãnh chúa Casterly Rock và Warden of the West trong cuộc nổi loạn Blackfyre đầu tiên.", culture: "Người miền Tây", bloodline: "Nhà Lannister", continent: "Westeros",
    appearance: "Không có mô tả ngoại hình canon xác thực.",
    name: "Damon Lannister",
    tuocVi: "Đại Lãnh Chúa",
    house: "Lannister",
    role: "Sư Tử Kiêu Hãnh",
    religion: "Thất Diện Thần",
    blurb: "Lãnh chúa của Casterly Rock, một người đã đứng về phía vua Daeron nhưng bị Fireball đánh bại trong các trận chiến ở Westerlands.",
    birthYear: 155,
    deathYear: 210,
    age: 41,
    coreStats: { "Sức Mạnh": 13, "Nhanh Nhẹn": 11, "Thể Chất": 12, "Trí Tuệ": 14, "Tinh Tường": 12, "Uy Tín": 15 },
    năngLực: { "Võ Lực": 65, "Thống Soái": 75, "Trí Mưu": 70, "Ngoại Giao": 60 },
    talentIds: ["merchant-fortune", "hot-tempered"],
    skills: { "command": 6, "court-etiquette": 8 },
    equipment: [],
    items: [],
    gold: 5000,
    startResources: {
      "Gỗ": 250,
      "Quặng Sắt": 750,
      "Đá": 750,
      "Lương Thực": 3000,
      "Ngựa": 100,
      "Thép Valyria": 0
    }, startingHookIds: [],
    allies: ["daeron-ii"],
    rivals: ["quentyn-ball", "daemon-blackfyre"],
    personalHooks: [
      { id: "damon-defense", title: "Phòng Thủ Casterly Rock", year: "196 AC", numericYear: 196, desc: "Lực lượng của Fireball đang tàn phá Westerlands. Ngươi phải bảo vệ kho vàng và vinh quang của nhà Lannister." }
    ],
    startArmies: [
          { name: "Vệ Binh Sư Tử Đỏ", type: "Bộ Binh", size: 24000, quality: "Tinh Nhuệ" },
          { name: "Kỵ Sĩ Vùng Đồi", type: "Kỵ Binh", size: 8000, quality: "Tinh Nhuệ" },
          { name: "Cung Thủ Phương Tây", type: "Cung Thủ", size: 8000, quality: "Tinh Nhuệ" }
        ],
    father: "",
    mother: "",
    spouse: "",
    children: [],
    siblings: [],
      startRegions: ["the-westerlands"],
      startHoldings: ["the-westerlands-seat"],
      holdingsLevel: {"the-westerlands-seat":5},
      baseIncome: 800
},
  {
    id: "otho-bracken",
    origin: "Hiệp sĩ Nhà Bracken ở Stone Hedge, chiến đấu cho Daemon Blackfyre tại Cánh Đồng Cỏ Đỏ.", culture: "Người Riverlands", bloodline: "Nhà Bracken", continent: "Westeros",
    appearance: "Không có mô tả ngoại hình canon xác thực.",
    name: "Otho Bracken",
    tuocVi: "Hiệp Sĩ",
    house: "Bracken",
    role: "Gã Tàn Bạo",
    religion: "Thất Diện Thần",
    blurb: "Được mệnh danh là 'Otho the Brute'. Hắn đã giết Lãnh chúa Quentyn Blackwood trong một giải đấu, khơi dậy mối thù đẫm máu. Trong cuộc nổi loạn, hắn chiến đấu vì Bittersteel và Blackfyre.",
    birthYear: 170,
    age: 26,
    coreStats: { "Sức Mạnh": 17, "Nhanh Nhẹn": 10, "Thể Chất": 18, "Trí Tuệ": 8, "Tinh Tường": 12, "Uy Tín": 8 },
    năngLực: { "Võ Lực": 85, "Thống Soái": 40, "Trí Mưu": 40, "Ngoại Giao": 60 },
    talentIds: ["warrior-blood", "berserker"],
    skills: { "axe-mace": 8, "sword-shield": 7 },
    equipment: [],
    items: [],
    gold: 300,
    startResources: {
      "Gỗ": 150,
      "Quặng Sắt": 40,
      "Đá": 100,
      "Lương Thực": 1000,
      "Ngựa": 20,
      "Thép Valyria": 0
    }, startingHookIds: [],
    allies: ["bittersteel", "daemon-blackfyre"],
    rivals: ["bloodraven"],
    personalHooks: [
      { id: "bracken-charge", title: "Otho Kẻ Tàn Bạo", year: "196 AC", numericYear: 196, desc: "Ngươi chém giết trên Cánh Đồng Cỏ Đỏ, tìm kiếm những cái đầu của gia tộc Blackwood." }
    ],
    father: "",
    mother: "",
    spouse: "",
    children: [],
    siblings: [],
    startArmies: [
          { name: "Dân Binh ", type: "Bộ Binh", size: 42, quality: "Mới Lập Đội" },
          { name: "Cung Thủ ", type: "Cung Thủ", size: 18, quality: "Mới Lập Đội" }
        ],
      startRegions: [],
      startHoldings: [],
      holdingsLevel: {},
      baseIncome: 25
}
];
