import type { CanonCharacter } from "../eras";

export const blackfyreRebellionCharacters: CanonCharacter[] = [
  {
    id: "baelor-breakspear",
    name: "Baelor Breakspear",
    tuocVi: "Hoàng Tử",
    house: "Targaryen",
    role: "Hoàng Tử Dragonstone",
    religion: "Thất Diện Thần",
    blurb: "Con trai trưởng và là người thừa kế của vua Daeron II. Baelor mang nhiều nét của người mẹ xứ Dorne với mái tóc đen và làn da ngăm. Anh là một chỉ huy lỗi lạc, người đã đập tan quân Blackfyre tại Cánh Đồng Cỏ Đỏ.",
    birthYear: 170,
    deathYear: 209,
    age: 26,
    coreStats: { STR: 15, AGI: 14, END: 15, INT: 16, WIL: 15, CHA: 18 },
    talentIds: ["born-leader", "honorable", "chivalrous"],
    skills: { "Chỉ Huy": 18, "Cận Chiến (Kiếm)": 15, "Cưỡi Ngựa": 14, "Ngoại Giao": 16 },
    equipment: [],
    items: [],
    gold: 2000,
    startingHookIds: [],
    personalHooks: [
      { id: "baelor-redgrass", title: "Cánh Đồng Cỏ Đỏ", year: "196 AC", numericYear: 196, desc: "Ngươi dẫn đầu đội quân Dorne và Stormlands đánh bọc sườn phiến quân Blackfyre. Chiến thắng hay thảm bại phụ thuộc vào nhát chùy của ngươi." }
    ]
  },
  {
    id: "maekar-i-targaryen",
    name: "Maekar Targaryen",
    tuocVi: "Hoàng Tử",
    house: "Targaryen",
    role: "Hoàng Tử Mùa Hè",
    religion: "Thất Diện Thần",
    blurb: "Con trai thứ tư của Daeron II. Khác với người anh Baelor hoàn hảo, Maekar gai góc, khắc nghiệt và mang nhiều mặc cảm. Dù vậy, cái đe của Maekar đã chặn đứng cuộc tiến công của phiến quân.",
    birthYear: 174,
    deathYear: 233,
    age: 22,
    coreStats: { STR: 16, AGI: 12, END: 16, INT: 12, WIL: 14, CHA: 10 },
    talentIds: ["stubborn", "fearsome-warrior", "pragmatic"],
    skills: { "Cận Chiến (Chùy)": 16, "Chỉ Huy": 15 },
    equipment: [],
    items: [],
    gold: 1500,
    startingHookIds: [],
    personalHooks: [
      { id: "maekar-anvil", title: "Cái Đe Của Maekar", year: "196 AC", numericYear: 196, desc: "Bức tường khiên của ngươi phải đứng vững trước cuộc tấn công mãnh liệt của Bittersteel, tạo thành cái đe cho chiếc búa của Baelor đập xuống." }
    ]
  },
  {
    id: "shiera-seastar",
    name: "Shiera Seastar",
    tuocVi: "Thường Dân",
    house: "Khác",
    role: "Ngôi Sao Biển",
    religion: "Thất Diện Thần",
    blurb: "Đứa con hoang xinh đẹp nhất của vua Aegon IV. Có hai màu mắt khác biệt và vẻ đẹp ma mị, Shiera luôn đứng giữa cuộc tình tay ba với Bloodraven và Bittersteel.",
    birthYear: 178,
    age: 18,
    coreStats: { STR: 5, AGI: 10, END: 8, INT: 18, WIL: 15, CHA: 20 },
    talentIds: ["seductive", "mystic", "intelligent"],
    skills: { "Thuyết Phục": 18, "Ma Thuật (Bóng Tối)": 14, "Quyến Rũ": 20 },
    equipment: [],
    items: [{ ten: "Dây Chuyền Sao Biển", soLuong: 1, moTa: "Sợi dây chuyền bạc điểm những viên ngọc bích và ngọc lục bảo." }],
    gold: 500,
    startingHookIds: [],
    personalHooks: [
      { id: "shiera-choice", title: "Lựa Chọn Của Ngôi Sao", year: "196 AC", numericYear: 196, desc: "Cả Bloodraven và Bittersteel đều cầu xin tình yêu của ngươi trước khi họ ra trận để chém giết lẫn nhau." }
    ]
  },
  {
    id: "gwayne-corbray",
    name: "Gwayne Corbray",
    tuocVi: "Hiệp Sĩ",
    house: "Corbray",
    role: "Hiệp Sĩ Vệ Vương",
    religion: "Thất Diện Thần",
    blurb: "Thành viên Vệ Vương, cầm thanh kiếm thép Valyria Lady Forlorn. Cuộc đấu tay đôi giữa ông và Daemon Blackfyre là một trong những trận chiến huyền thoại nhất.",
    birthYear: 165,
    deathYear: 196,
    age: 31,
    coreStats: { STR: 15, AGI: 16, END: 15, INT: 10, WIL: 14, CHA: 12 },
    talentIds: ["loyal", "chivalrous", "fearsome-warrior"],
    skills: { "Cận Chiến (Kiếm)": 18, "Cưỡi Ngựa": 14 },
    equipment: [{ slot: "Tay Phải", ten: "Lady Forlorn", phamChat: "Thép Valyria", thuocTinh: { "Sát Thương": 25 }, moTa: "Thanh kiếm Thép Valyria của Nhà Corbray." }],
    items: [],
    gold: 50,
    startingHookIds: [],
    personalHooks: [
      { id: "corbray-duel", title: "Cuộc Đấu Huyền Thoại", year: "196 AC", numericYear: 196, desc: "Trực diện với Daemon Blackfyre. Lady Forlorn chạm trán thanh Blackfyre trong tiếng gầm thét của hàng vạn binh lính." }
    ]
  },
  {
    id: "quentyn-ball",
    name: "Quentyn Ball",
    tuocVi: "Hiệp Sĩ",
    house: "Ball",
    role: "Quả Cầu Lửa",
    religion: "Thất Diện Thần",
    blurb: "Được mệnh danh là 'Fireball'. Bị từ chối vị trí trong Vệ Vương, Quentyn mang mối thù sâu sắc và trở thành một trong những chỉ huy xuất sắc nhất của quân Blackfyre.",
    birthYear: 160,
    deathYear: 196,
    age: 36,
    coreStats: { STR: 16, AGI: 15, END: 16, INT: 12, WIL: 15, CHA: 14 },
    talentIds: ["fearsome-warrior", "vengeful", "ambitious"],
    skills: { "Cận Chiến (Kiếm)": 17, "Chỉ Huy": 15 },
    equipment: [],
    items: [],
    gold: 200,
    startingHookIds: [],
    personalHooks: [
      { id: "fireball-strike", title: "Cơn Phẫn Nộ Của Fireball", year: "196 AC", numericYear: 196, desc: "Ngươi vượt sông Mander, đánh úp quân trung thành và tiêu diệt hoàn toàn gia tộc Lefford." }
    ]
  },
  {
    id: "robb-reyne",
    name: "Robb Reyne",
    tuocVi: "Hiệp Sĩ",
    house: "Reyne",
    role: "Sư Tử Đỏ",
    religion: "Thất Diện Thần",
    blurb: "Một hiệp sĩ hào hoa và là một trong những tay kiếm xuất sắc nhất thời đại, phục vụ dưới trướng Daemon Blackfyre.",
    birthYear: 168,
    age: 28,
    coreStats: { STR: 15, AGI: 16, END: 14, INT: 10, WIL: 12, CHA: 16 },
    talentIds: ["chivalrous", "arrogant", "handsome"],
    skills: { "Cận Chiến (Kiếm)": 16, "Cưỡi Ngựa": 15 },
    equipment: [],
    items: [],
    gold: 800,
    startingHookIds: [],
    startHoldings: [],
    startRegions: [],
    personalHooks: [
      { id: "reyne-charge", title: "Tiếng Gầm Sư Tử Đỏ", year: "196 AC", numericYear: 196, desc: "Ngươi dẫn đầu kỵ binh tấn công vào sườn đội hình quân Targaryen." }
    ]
  },
  {
    id: "leo-tyrell",
    name: "Leo Tyrell",
    tuocVi: "Lãnh Chúa",
    house: "Tyrell",
    role: "Gai Dài",
    religion: "Thất Diện Thần",
    blurb: "Lãnh chúa Leo 'Longthorn' Tyrell, một hiệp sĩ lừng danh của giải đấu, và là người đã đánh bại phe Blackfyre tại vùng Reach, dù không đến kịp trận Cánh Đồng Cỏ Đỏ.",
    birthYear: 160,
    age: 36,
    coreStats: { STR: 14, AGI: 15, END: 14, INT: 13, WIL: 14, CHA: 16 },
    talentIds: ["chivalrous", "born-leader", "wealthy"],
    skills: { "Thương Kỵ": 18, "Cận Chiến (Kiếm)": 14, "Chỉ Huy": 14 },
    equipment: [],
    items: [],
    gold: 4000,
    startingHookIds: [],
    startHoldings: ["highgarden"],
    startRegions: ["the-reach"],
    personalHooks: [
      { id: "longthorn-reach", title: "Bảo Vệ Vùng Reach", year: "196 AC", numericYear: 196, desc: "Trong khi các trận chiến lớn diễn ra ở phía Bắc, ngươi phải dọn dẹp các lãnh chúa phản nghịch ngay trong sân nhà mình." }
    ]
  },
  {
    id: "donnel-arryn",
    name: "Donnel Arryn",
    tuocVi: "Lãnh Chúa",
    house: "Arryn",
    role: "Lãnh Chúa Eyrie",
    religion: "Thất Diện Thần",
    blurb: "Người chỉ huy quân đội tiên phong của Targaryen tại Cánh Đồng Cỏ Đỏ, nhưng hàng ngũ của ông đã bị Daemon Blackfyre đập tan.",
    birthYear: 160,
    deathYear: 209,
    age: 36,
    coreStats: { STR: 12, AGI: 12, END: 13, INT: 12, WIL: 14, CHA: 14 },
    talentIds: ["honorable", "born-leader"],
    skills: { "Chỉ Huy": 14, "Cận Chiến (Kiếm)": 12 },
    equipment: [],
    items: [],
    gold: 1500,
    startingHookIds: [],
    startHoldings: ["the-eyrie"],
    startRegions: ["the-vale"],
    personalHooks: [
      { id: "donnel-vanguard", title: "Tiên Phong Thất Bại", year: "196 AC", numericYear: 196, desc: "Ngươi dẫn quân tiên phong đối mặt với Daemon Blackfyre và thanh gươm của vương triều. Ngươi biết mình không có cơ hội." }
    ]
  },
  {
    id: "damon-lannister",
    name: "Damon Lannister",
    tuocVi: "Lãnh Chúa",
    house: "Lannister",
    role: "Sư Tử Kiêu Hãnh",
    religion: "Thất Diện Thần",
    blurb: "Lãnh chúa của Casterly Rock, một người đã đứng về phía vua Daeron nhưng bị Fireball đánh bại trong các trận chiến ở Westerlands.",
    birthYear: 155,
    deathYear: 210,
    age: 41,
    coreStats: { STR: 13, AGI: 11, END: 12, INT: 14, WIL: 12, CHA: 15 },
    talentIds: ["wealthy", "arrogant"],
    skills: { "Chỉ Huy": 12, "Quản Lý": 15 },
    equipment: [],
    items: [],
    gold: 5000,
    startingHookIds: [],
    startHoldings: ["casterly-rock"],
    startRegions: ["the-westerlands"],
    personalHooks: [
      { id: "damon-defense", title: "Phòng Thủ Casterly Rock", year: "196 AC", numericYear: 196, desc: "Lực lượng của Fireball đang tàn phá Westerlands. Ngươi phải bảo vệ kho vàng và vinh quang của nhà Lannister." }
    ]
  },
  {
    id: "otho-bracken",
    name: "Otho Bracken",
    tuocVi: "Hiệp Sĩ",
    house: "Bracken",
    role: "Gã Tàn Bạo",
    religion: "Thất Diện Thần",
    blurb: "Được mệnh danh là 'Otho the Brute'. Hắn đã giết Lãnh chúa Quentyn Blackwood trong một giải đấu, khơi dậy mối thù đẫm máu. Trong cuộc nổi loạn, hắn chiến đấu vì Bittersteel và Blackfyre.",
    birthYear: 170,
    age: 26,
    coreStats: { STR: 17, AGI: 10, END: 18, INT: 8, WIL: 12, CHA: 8 },
    talentIds: ["fearsome-warrior", "brutal"],
    skills: { "Cận Chiến (Rìu)": 15, "Cận Chiến (Kiếm)": 14 },
    equipment: [],
    items: [],
    gold: 300,
    startingHookIds: [],
    startHoldings: [],
    startRegions: [],
    personalHooks: [
      { id: "bracken-charge", title: "Otho Kẻ Tàn Bạo", year: "196 AC", numericYear: 196, desc: "Ngươi chém giết trên Cánh Đồng Cỏ Đỏ, tìm kiếm những cái đầu của gia tộc Blackwood." }
    ]
  }
];
