import type { CanonCharacter } from "../eras";

export const dawnAgeCharacters: CanonCharacter[] = [
  {
    id: "lann-the-clever", name: "Lann Kẻ Trí", house: "Lannister", role: "Kẻ Lừa Đảo Huyền Thoại", tuocVi: "Quốc Vương", religion: "Cựu Thần",
    blurb: "Truyền thuyết kể rằng hắn đã lừa dòng dõi Casterly để lấy đi Casterly Rock chỉ bằng trí óc. Trở thành vị Vua của the Rock.",
    birthYear: -8050, age: 30, coreStats: { "Sức Mạnh": 8, "Nhanh Nhẹn": 16, "Thể Chất": 10, "Trí Tuệ": 20, "Tinh Tường": 18, "Uy Tín": 18 },
    talentIds: ["schemer", "silver-tongue"],
    skills: { "cunning": 10, "stealth": 9, "persuasion": 10, "commerce": 8, "command": 7 },
    equipment: [{ slot: "Vũ Khí Phụ", ten: "Dao găm mạ vàng", phamChat: "Tinh Xảo", thuocTinh: { "Sát Thương Cận": 4 }, moTa: "Dao giấu trong tay áo." }], 
    items: [{ ten: "Vàng Casterly", soLuong: 100000, moTa: "Khởi đầu của huyền thoại" }], 
    gold: 150000, startingHookIds: [], startHoldings: ["the-westerlands-seat"], startRegions: ["the-westerlands"],
    rivals: ["garth-greenhand"],
    startArmy: { size: 30000, quality: "Tinh Nhuệ" },
    baseIncome: 800,
    holdingsLevel: { "the-westerlands-seat": 5 },
    father: "rowan-gold-tree", // Theo một số truyền thuyết
    mother: "",
    spouse: "",
    children: [], // Rất nhiều con nhưng không rõ tên trong game
    siblings: [],
    allies: []
  },
  {
    id: "garth-greenhand", name: "Garth Bàn Tay Xanh", house: "Gardener", role: "Vị Thần Của Đất", tuocVi: "Quốc Vương", religion: "Cựu Thần",
    blurb: "Tổ tiên của mọi gia tộc lớn ở Reach. Đi tới đâu, cây cỏ tốt tươi tới đó, phụ nữ mang thai, vụ mùa bội thu.",
    birthYear: -8080, age: 60, coreStats: { "Sức Mạnh": 15, "Nhanh Nhẹn": 10, "Thể Chất": 18, "Trí Tuệ": 16, "Tinh Tường": 15, "Uy Tín": 20 },
    talentIds: ["beloved", "giant-frame"],
    skills: { "animal-handling": 10, "weather-endurance": 8, "persuasion": 9, "command": 8 },
    equipment: [{ slot: "Vật Phẩm Đặc Biệt", ten: "Vương miện hoa lá", phamChat: "Vô Giá", thuocTinh: { "Tôn Trọng": 15 }, moTa: "Được đan từ dây leo, không bao giờ héo" }], 
    items: [{ ten: "Hạt giống thần kỳ", soLuong: 100, moTa: "Rải xuống là mọc thành rừng" }], 
    gold: 50000, startingHookIds: [], startHoldings: ["the-reach-seat"], startRegions: ["the-reach"],
    rivals: ["lann-the-clever", "durran-godsgrief"],
    startArmy: { size: 60000, quality: "Thành Thạo" },
    baseIncome: 1200,
    holdingsLevel: { "the-reach-seat": 5 },
    father: "",
    mother: "",
    spouse: "",
    children: ["garth-the-gardener", "rowan-gold-tree"], 
    siblings: [],
    allies: []
  },
  {
    id: "durran-godsgrief", name: "Durran Than Thở Trời", house: "Durrandon", role: "Người Xây Storm's End", tuocVi: "Quốc Vương", religion: "Cựu Thần",
    blurb: "Kẻ dám yêu con gái thần Gió và Biển, và xây dựng Storm's End để thách thức cơn thịnh nộ của họ. Khởi thủy của Vua Bão.",
    birthYear: -8060, age: 40, coreStats: { "Sức Mạnh": 20, "Nhanh Nhẹn": 11, "Thể Chất": 20, "Trí Tuệ": 12, "Tinh Tường": 13, "Uy Tín": 16 },
    talentIds: ["hot-tempered", "warrior-blood", "giant-frame"],
    skills: { "command": 10, "weather-endurance": 10, "intimidation": 9, "sword-shield": 10 },
    equipment: [{ slot: "Vũ Khí Chính", ten: "Búa Vua Bão", phamChat: "Thượng Hạng", thuocTinh: { "Sát Thương Cận": 10 }, moTa: "Đập tan cơn bão và kẻ thù" }], 
    items: [], 
    gold: 15000, startingHookIds: [], startHoldings: ["the-stormlands-seat"], startRegions: ["the-stormlands"],
    spouse: "elenei",
    allies: ["brandon-builder"],
    startArmy: { size: 35000, quality: "Thành Thạo" },
    baseIncome: 400,
    holdingsLevel: { "the-stormlands-seat": 5 },
    father: "",
    mother: "",
    children: ["durran-the-devout"],
    siblings: [],
    rivals: ["sea-god", "wind-goddess"]
  },
  {
    id: "grey-king", name: "Vua Xám", house: "Greyiron", role: "Vua Đảo Sắt Đầu Tiên", tuocVi: "Quốc Vương", religion: "Thần Chết Chìm",
    blurb: "Giết rồng biển Nagga, lấy xương làm ngai. Tóc, râu và mắt đều xám màu biển động. Cai trị Quần Đảo Sắt hơn một ngàn năm.",
    birthYear: -8100, age: 80, coreStats: { "Sức Mạnh": 18, "Nhanh Nhẹn": 12, "Thể Chất": 20, "Trí Tuệ": 14, "Tinh Tường": 16, "Uy Tín": 19 },
    talentIds: ["warrior-blood", "ironborn"],
    skills: { "sailing": 10, "axe-mace": 10, "weather-endurance": 10, "command": 9 },
    equipment: [{ slot: "Vật Phẩm Đặc Biệt", ten: "Vương miện gỗ lũa", phamChat: "Vô Giá", thuocTinh: { "Tôn Trọng": 15 }, moTa: "Vương miện của Đảo Sắt" }], 
    items: [{ ten: "Răng rồng biển Nagga", soLuong: 1, moTa: "To như thanh gươm" }], 
    gold: 8000, startingHookIds: [], startHoldings: ["the-iron-islands-seat"], startRegions: ["the-iron-islands"],
    startArmy: { size: 10000, quality: "Thành Thạo" }, // Quân Đảo Sắt không quá đông trên bộ
    baseIncome: 200,
    holdingsLevel: { "the-iron-islands-seat": 4 },
    father: "",
    mother: "",
    spouse: "mermaid",
    children: [], // Hàng trăm con trai
    siblings: [],
    allies: [],
    rivals: ["nagga-sea-dragon"]
  },
  {
    id: "symeon-star-eyes", name: "Symeon Mắt Sao", house: "Không Nhà", role: "Hiệp Sĩ Mù", tuocVi: "Hiệp Sĩ", religion: "Cựu Thần",
    blurb: "Một hiệp sĩ huyền thoại mù lòa, đặt hai viên ngọc sapphire vào hốc mắt và sử dụng trường thương múa với hai đầu sắc bén.",
    birthYear: -8040, age: 35, coreStats: { "Sức Mạnh": 16, "Nhanh Nhẹn": 20, "Thể Chất": 15, "Trí Tuệ": 13, "Tinh Tường": 5, "Uy Tín": 14 },
    talentIds: ["born-swordsman", "duelist"],
    skills: { "sword-shield": 10, "brawling": 8, "cunning": 6, "animal-handling": 5 },
    equipment: [{ slot: "Vũ Khí Chính", ten: "Thương hai đầu", phamChat: "Tinh Xảo", thuocTinh: { "Sát Thương Cận": 8 }, moTa: "Xoay tít như cối xay" }, { slot: "Vật Phẩm Đặc Biệt", ten: "Mặt nạ che hốc mắt", phamChat: "Thường", thuocTinh: { "Phòng Thủ": 1 }, moTa: "Che đi viên ngọc sao" }], 
    items: [{ ten: "Ngọc Sapphire", soLuong: 2, moTa: "Thay thế cho đôi mắt" }], 
    gold: 200, startingHookIds: [],
    father: "",
    mother: "",
    spouse: "",
    children: [],
    siblings: [],
    allies: [],
    rivals: [],
    startArmy: { size: 0, quality: "Mới Lập Đội" },
    baseIncome: 10,
    holdingsLevel: {}
  }
];
